[package]
name = "pi_calculator"
version = "0.1.0"
authors = ["Przemysław Rachwał <przemyslaw.rachwal@gmail.com>"]
license = "MIT"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "pi_calculator"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.10.1"

[dependencies]
neon = "1.0.0"
